# config.yaml - Complete Configuration

# Model Configurations
models:
  logistic_regression:
    multi_class: 'multinomial'
    solver: 'lbfgs'
    max_iter: 1000
    random_state: 42
    class_weight: 'balanced'
    C: 1.0
    penalty: 'l2'
  
  decision_tree:
    max_depth: 10
    random_state: 42
    class_weight: 'balanced'
    min_samples_split: 2
    min_samples_leaf: 1
    criterion: 'gini'
  
  neural_network:
    hidden_layer_sizes: [100, 50]
    max_iter: 1000
    random_state: 42
    early_stopping: True
    learning_rate: 'adaptive'
    learning_rate_init: 0.001
    alpha: 0.0001
    activation: 'relu'
  
  svm:
    kernel: 'linear'
    probability: True
    random_state: 42
    class_weight: 'balanced'
    C: 1.0
    gamma: 'scale'
    decision_function_shape: 'ovr'
  
  lasso_regression:
    multi_class: 'multinomial'
    solver: 'saga'
    max_iter: 1000
    random_state: 42
    class_weight: 'balanced'
    C: 1.0
    penalty: 'l1'

# Feature Engineering Configuration
feature_engineering:
  tfidf:
    max_features: 1000
    stop_words: 'english'
    ngram_range: [1, 2]
    min_df: 1
    max_df: 1.0

# Training Configuration
training:
  num_chunks: 10
  random_state: 42
  primary_metric: 'f1_score'
  test_size: 0.2

# Drift Detection Configuration
drift_detection:
  data_drift_threshold: 0.01
  concept_drift_threshold: 0.006
  significance_level: 0.006

# Paths Configuration
paths:
  # Input paths
  balanced_dataset: "balanced_dataset"
  train_dataset: "train_test_data/train_data.csv"
  test_dataset: "train_test_data/test_data.csv"
  
  # Output directories
  chunks_dir: "chunks"
  models_dir: "models"
  best_models_dir: "best_models"
  reports_dir: "reports"
  drift_reports_dir: "drift_reports"
  
  # File names
  drift_file: "test_data_drift_report.pkl"
  overall_best_model: "overall_best_model.pkl"